# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vinayak/redx/ProstheticEye

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vinayak/redx/ProstheticEye

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vinayak/redx/ProstheticEye/CMakeFiles /home/vinayak/redx/ProstheticEye/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vinayak/redx/ProstheticEye/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named deluanay_graph

# Build rule for target.
deluanay_graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deluanay_graph
.PHONY : deluanay_graph

# fast build rule for target.
deluanay_graph/fast:
	$(MAKE) -f CMakeFiles/deluanay_graph.dir/build.make CMakeFiles/deluanay_graph.dir/build
.PHONY : deluanay_graph/fast

#=============================================================================
# Target rules for targets named symmetry

# Build rule for target.
symmetry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 symmetry
.PHONY : symmetry

# fast build rule for target.
symmetry/fast:
	$(MAKE) -f CMakeFiles/symmetry.dir/build.make CMakeFiles/symmetry.dir/build
.PHONY : symmetry/fast

#=============================================================================
# Target rules for targets named ui

# Build rule for target.
ui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ui
.PHONY : ui

# fast build rule for target.
ui/fast:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/build
.PHONY : ui/fast

deluanay_graph.o: deluanay_graph.cpp.o
.PHONY : deluanay_graph.o

# target to build an object file
deluanay_graph.cpp.o:
	$(MAKE) -f CMakeFiles/deluanay_graph.dir/build.make CMakeFiles/deluanay_graph.dir/deluanay_graph.cpp.o
.PHONY : deluanay_graph.cpp.o

deluanay_graph.i: deluanay_graph.cpp.i
.PHONY : deluanay_graph.i

# target to preprocess a source file
deluanay_graph.cpp.i:
	$(MAKE) -f CMakeFiles/deluanay_graph.dir/build.make CMakeFiles/deluanay_graph.dir/deluanay_graph.cpp.i
.PHONY : deluanay_graph.cpp.i

deluanay_graph.s: deluanay_graph.cpp.s
.PHONY : deluanay_graph.s

# target to generate assembly for a file
deluanay_graph.cpp.s:
	$(MAKE) -f CMakeFiles/deluanay_graph.dir/build.make CMakeFiles/deluanay_graph.dir/deluanay_graph.cpp.s
.PHONY : deluanay_graph.cpp.s

symmetry.o: symmetry.cpp.o
.PHONY : symmetry.o

# target to build an object file
symmetry.cpp.o:
	$(MAKE) -f CMakeFiles/symmetry.dir/build.make CMakeFiles/symmetry.dir/symmetry.cpp.o
.PHONY : symmetry.cpp.o

symmetry.i: symmetry.cpp.i
.PHONY : symmetry.i

# target to preprocess a source file
symmetry.cpp.i:
	$(MAKE) -f CMakeFiles/symmetry.dir/build.make CMakeFiles/symmetry.dir/symmetry.cpp.i
.PHONY : symmetry.cpp.i

symmetry.s: symmetry.cpp.s
.PHONY : symmetry.s

# target to generate assembly for a file
symmetry.cpp.s:
	$(MAKE) -f CMakeFiles/symmetry.dir/build.make CMakeFiles/symmetry.dir/symmetry.cpp.s
.PHONY : symmetry.cpp.s

ui.o: ui.cpp.o
.PHONY : ui.o

# target to build an object file
ui.cpp.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui.cpp.o
.PHONY : ui.cpp.o

ui.i: ui.cpp.i
.PHONY : ui.i

# target to preprocess a source file
ui.cpp.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui.cpp.i
.PHONY : ui.cpp.i

ui.s: ui.cpp.s
.PHONY : ui.s

# target to generate assembly for a file
ui.cpp.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui.cpp.s
.PHONY : ui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... deluanay_graph"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... symmetry"
	@echo "... ui"
	@echo "... deluanay_graph.o"
	@echo "... deluanay_graph.i"
	@echo "... deluanay_graph.s"
	@echo "... symmetry.o"
	@echo "... symmetry.i"
	@echo "... symmetry.s"
	@echo "... ui.o"
	@echo "... ui.i"
	@echo "... ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

