#include <../ProstheticEye/symmetry.hpp>

typedef pcl::visualization::PCLVisualizer Visualizer;
typedef std::tuple<float,float,float> plane;

boost::shared_ptr<Visualizer> makeVisualizer(){
	boost::shared_ptr<Visualizer> viewer (new Visualizer ("3D Viewer"));
	viewer->setBackgroundColor (0, 0, 0);
	viewer->initCameraParameters ();
	return (viewer);
}

void addCloud(boost::shared_ptr<Visualizer> viewer,pcl::PointCloud<pcl::PointXYZ>::ConstPtr cloud,const std::string &label){
	viewer->addPointCloud<pcl::PointXYZ> (cloud, label.c_str());
	viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, label.c_str());
}

void addRedCloud(boost::shared_ptr<Visualizer> viewer,pcl::PointCloud<pcl::PointXYZ>::ConstPtr cloud,const std::string &label){
	pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZ> single_color(cloud, 255, 0, 0);
    viewer->addPointCloud<pcl::PointXYZ> (cloud, single_color, label.c_str());
    viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 3, label.c_str());
}

float planeMaker(const float x,const float y,const plane &p){
	const float a = std::get<0>(p);
	const float b = std::get<1>(p);
	const float c = std::get<2>(p);
	return (a*a+b*b+c*c - a*x - b*y)/c;
}

int main(){
	srand(time(NULL));
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>());
	readfsamp("../ProstheticEye/Full_face.xyz",cloud); //Vinayak face - post processed to remove sparse points, and cut for hair and regions below chin
	//readfsamp("../ProstheticEye/0_31_eyes.xyz",cloud);
	auto v = makeVisualizer();
	addCloud(v,cloud,"cloud");
	//plane p(0.032072,0.031865,0.129676); //Scan 2
	//plane p(0.031160,-0.006922,-0.032507); //Scan 2
	plane p(9.327223,0.468285,0.717058); //Vinayak face - working - it is the mode 
										 //generated by ./MeanShift for bandwidth = 41 using the epanechnikov kernel
	//plane p(0.018255,13.568290,-3.263638); //exenterated face - scan too small to detect symmetry
	pcl::PointCloud<pcl::PointXYZ>::Ptr plane_cloud(new pcl::PointCloud<pcl::PointXYZ>());
	for(int i=0;i<10000;i++){
		float x = ((float)(rand()%6000))/100.0 - 40.0;
		float y = ((float)(rand()%3000))/10.0 - 100.0;
		float z = planeMaker(x,y,p);
		plane_cloud->points.push_back(pcl::PointXYZ(x,y,z));
	}
	addRedCloud(v,plane_cloud,"plane1");
	while(!v->wasStopped()){
		v->spinOnce(100);
		boost::this_thread::sleep(boost::posix_time::microseconds(10000));
	}
}